package com.gcp.agents.cli.ci.github

/**
 * GitHubActionWrapper — JavaScript action 封装
 * JavaScript action wrapper for GitHub Actions integration.
 *
 * 生成 GitHub Actions action.yml 和 wrapper 代码
 * Generates GitHub Actions action.yml and wrapper code.
 */
class GitHubActionWrapper {

    /**
     * 生成 action.yml 内容 / Generate action.yml content
     */
    fun generateActionYaml(): String {
        return """
            # Generated by agents-cli-sdk
            name: 'agents-cli-sdk-deploy'
            description: 'Deploy agents using Google agents-cli SDK'
            author: 'Enterprise DevOps'
            inputs:
              agent-name:
                description: 'Name of the agent to deploy'
                required: true
              target-service:
                description: 'Target GCP service (vertex-ai, cloud-run, gke)'
                required: true
                default: 'vertex-ai'
              iam-policy:
                description: 'GCP IAM policy JSON'
                required: false
              quota-limit:
                description: 'Hourly quota limit'
                required: false
                default: '10000'
              audit-export:
                description: 'Audit export destination (bigquery, gcs, splunk)'
                required: false
                default: 'bigquery'
              audit-project:
                description: 'Audit GCP project ID'
                required: false
              gcp-credentials:
                description: 'GCP service account JSON (use secrets)'
                required: true
            outputs:
              endpoint:
                description: 'Deployed agent endpoint'
              instance-id:
                description: 'Agent instance ID'
            runs:
              using: 'node20'
              main: 'dist/index.js'
            branding:
              color: 'blue'
              icon: 'cloud'
        """.trimIndent()
    }

    /**
     * 生成 JavaScript wrapper 代码 / Generate JavaScript wrapper code
     */
    fun generateWrapperCode(): String {
        return """
            // Generated by agents-cli-sdk
            const core = require('@actions/core');
            const exec = require('@actions/exec');
            const fs = require('fs');

            async function run() {
                try {
                    const agentName = core.getInput('agent-name');
                    const targetService = core.getInput('target-service');
                    const iamPolicy = core.getInput('iam-policy');
                    const quotaLimit = core.getInput('quota-limit');
                    const gcpCredentials = core.getInput('gcp-credentials');

                    // Write credentials to temp file
                    const credPath = '/tmp/gcp-sa-key.json';
                    fs.writeFileSync(credPath, gcpCredentials);
                    process.env.GOOGLE_APPLICATION_CREDENTIALS = credPath;

                    let cmd = ['agents-cli', 'agent', 'deploy', '--name', agentName, '--target', targetService];
                    await exec.exec(cmd[0], cmd.slice(1));
                    console.log('[agents-cli-sdk] Deployment completed');
                } catch (error) {
                    core.setFailed(error.message);
                    process.exit(1);
                }
            }
            run();
        """.trimIndent()
    }

    /**
     * 生成完整的 action 目录结构 / Generate complete action directory structure
     */
    fun generateActionFiles(): Map<String, String> {
        return mapOf(
            "action.yml" to generateActionYaml(),
            "src/index.js" to generateWrapperCode()
        )
    }
}
