package com.mvi.kenny.feature.geminitest

// ================================================================
// GeminiTestQualityContract — Gemini Test Generation Toolkit MVI Contract
// ================================================================
// MVI architecture contract for Android Studio Panda 4 Gemini Unit Test
// Generation Toolkit.
//
// PRD-104: Android Studio Panda 4 Gemini 单元测试生成工具包
// Design Reference: memory/agency/designs/PRD-104-Android-Studio-Panda-4-Gemini-单元测试生成工具包.md
//
// MVI 三要素 / Three pillars:
//   Model (State)  — Immutable page state, single source of truth
//   View           — Composable function, consumes State, renders UI
//   Intent         — User intentions, ViewModel processes and updates State
//   Effect         — One-time side effects (navigation, toast), via Channel
// ================================================================

// ================================================================
// Enums / 枚举
// ================================================================

/**
 * ============================================================
 * TestQualityTab — 工具包 Tab 导航枚举
 * ================================================================
 * Six main tabs in the Gemini Test Quality Hub.
 *
 * @param titleCn 中文标题
 */
enum class TestQualityTab(val titleCn: String) {
    Dashboard("质量仪表盘"),
    CustomGenerator("框架定制"),
    SpecEngine("规范引擎"),
    Traceability("可追溯性"),
    BlindSpot("盲区分析"),
    CIIntegration("CI/CD 集成")
}

/**
 * ============================================================
 * TestFramework — 测试框架枚举
 * ================================================================
 * Supported testing frameworks for Gemini test generation.
 *
 * @param displayName 中文显示名称
 */
enum class TestFramework(val displayName: String) {
    JUNIT4("JUnit 4"),
    JUNIT5("JUnit 5"),
    MOCKITO("Mockito"),
    KOTEST("Kotest")
}

/**
 * ============================================================
 * CoverageLevel — 覆盖率等级枚举
 * ================================================================
 * Coverage quality levels with color coding.
 *
 * @param colorHex RGB hex color for UI
 */
enum class CoverageLevel(val colorHex: Long) {
    High(0xFF34C759),    // Green — 80%+
    Medium(0xFFFFD60A),  // Yellow — 50-79%
    Low(0xFFFF9F0A),    // Orange — 20-49%
    Critical(0xFFFF453A) // Red — <20%
}

/**
 * ============================================================
 * BlindSpotSeverity — 盲区严重程度枚举
 * ================================================================
 * Severity classification for detected blind spots.
 *
 * @param displayName 中文显示名称
 * @param colorHex RGB hex color
 */
enum class BlindSpotSeverity(val displayName: String, val colorHex: Long) {
    Critical("严重", 0xFFFF453A),
    Warning("警告", 0xFFFF9F0A),
    Info("提示", 0xFF4285F4)
}

/**
 * ============================================================
 * CIProvider — CI 提供商枚举
 * ================================================================
 * Supported CI/CD providers for test integration.
 *
 * @param displayName 中文显示名称
 * @param yamlFileName Default workflow file name
 */
enum class CIProvider(val displayName: String, val yamlFileName: String) {
    GitHubActions("GitHub Actions", ".github/workflows/gemini-tests.yml"),
    GitLabCI("GitLab CI", ".gitlab-ci.yml")
}

// ================================================================
// Data Models / 数据模型
// ================================================================

/**
 * ============================================================
 * GeneratedTestFile — Gemini 生成的测试文件
 * ================================================================
 * Represents a test file generated by Gemini.
 *
 * @param id Unique identifier
 * @param sourceFileName Original source file name
 * @param testFileName Generated test file name
 * @param framework Test framework used
 * @param qualityScore Overall quality score (0-100)
 * @param branchCoverage Branch coverage percentage
 * @param conditionCoverage Condition coverage percentage
 * @param pathCoverage Path coverage percentage
 * @param generatedAt Timestamp of generation
 * @param testCaseCount Number of test cases
 * @param missingRiskCount Number of missing risk points
 */
data class GeneratedTestFile(
    val id: String,
    val sourceFileName: String,
    val testFileName: String,
    val framework: TestFramework,
    val qualityScore: Int,          // 0-100
    val branchCoverage: Float,      // 0.0-1.0
    val conditionCoverage: Float,    // 0.0-1.0
    val pathCoverage: Float,         // 0.0-1.0
    val generatedAt: String,
    val testCaseCount: Int,
    val missingRiskCount: Int
)

/**
 * ============================================================
 * QualityScore — 质量评分聚合
 * ================================================================
 * Aggregated quality metrics for dashboard display.
 *
 * @param overall Overall quality score (0-100)
 * @param branchCoverage Branch coverage (0.0-1.0)
 * @param conditionCoverage Condition coverage (0.0-1.0)
 * @param pathCoverage Path coverage (0.0-1.0)
 * @param boundaryCoverage Boundary coverage (0.0-1.0)
 * @param exceptionHandling Exception handling score (0.0-1.0)
 */
data class QualityScore(
    val overall: Int = 0,
    val branchCoverage: Float = 0f,
    val conditionCoverage: Float = 0f,
    val pathCoverage: Float = 0f,
    val boundaryCoverage: Float = 0f,
    val exceptionHandling: Float = 0f
)

/**
 * ============================================================
 * BranchCoverage — 分支覆盖率详情
 * ================================================================
 * Branch-level coverage data for heatmap display.
 *
 * @param fileName Source file name
 * @param branchName Branch/condition name
 * @param lineNumber Source line number
 * @param coverage Coverage ratio (0.0-1.0)
 * @param level Coverage level (High/Medium/Low/Critical)
 */
data class BranchCoverage(
    val fileName: String,
    val branchName: String,
    val lineNumber: Int,
    val coverage: Float,
    val level: CoverageLevel
)

/**
 * ============================================================
 * TestSpecTemplate — 测试规范模板
 * ================================================================
 * Team-defined test specification template.
 *
 * @param id Unique identifier
 * @param name Template name
 * @param description Template description
 * @param namingRule Naming convention rule
 * @param commentStyle Comment style requirement
 * @param boundaryRule Boundary value testing requirement
 * @param mockRule Mock usage specification
 * @param isActive Whether this template is currently active
 */
data class TestSpecTemplate(
    val id: String,
    val name: String,
    val description: String,
    val namingRule: String = "MethodName_ShouldExpectedBehavior_WhenCondition",
    val commentStyle: String = "// Arrange / Act / Assert",
    val boundaryRule: String = "Test edge cases: min, max, min-1, max+1",
    val mockRule: String = "Use @Mock for dependencies, @InjectMocks for SUT",
    val isActive: Boolean = false
)

/**
 * ============================================================
 * CoverageStrategy — 覆盖策略配置
 * ================================================================
 * Configuration for test generation coverage strategy.
 *
 * @param enableBoundaryValue Enable boundary value testing
 * @param enableEquivalenceClass Enable equivalence class partitioning
 * @param enablePathCoverage Enable path coverage strategy
 * @param enableExceptionPath Enable exception path testing
 */
data class CoverageStrategy(
    val enableBoundaryValue: Boolean = true,
    val enableEquivalenceClass: Boolean = true,
    val enablePathCoverage: Boolean = false,
    val enableExceptionPath: Boolean = true
)

/**
 * ============================================================
 * TraceabilityRecord — 可追溯性记录
 * ================================================================
 * Source code change → test impact mapping record.
 *
 * @param id Unique identifier
 * @param sourceFileName Changed source file
 * @param changedAt Change timestamp
 * @param changeType Type of change (ADD/MODIFY/DELETE)
 * @param impactedTests List of impacted test file names
 * @param regressionNeeded Whether regression testing is needed
 */
data class TraceabilityRecord(
    val id: String,
    val sourceFileName: String,
    val changedAt: String,
    val changeType: String,  // ADD / MODIFY / DELETE
    val impactedTests: List<String>,
    val regressionNeeded: Boolean
)

/**
 * ============================================================
 * BlindSpot — 测试盲区
 * ================================================================
 * Uncovered code path detected by blind spot analyzer.
 *
 * @param id Unique identifier
 * @param fileName Source file containing blind spot
 * @param methodName Method name with blind spot
 * @param lineNumber Line number
 * @param description Human-readable description
 * @param severity Blind spot severity level
 * @param suggestedTestcases Suggested test cases to cover
 */
data class BlindSpot(
    val id: String,
    val fileName: String,
    val methodName: String,
    val lineNumber: Int,
    val description: String,
    val severity: BlindSpotSeverity,
    val suggestedTestcases: List<String>
)

/**
 * ============================================================
 * CIConfig — CI/CD 配置
 * ================================================================
 * Generated CI/CD configuration for automated testing.
 *
 * @param provider CI provider (GitHubActions/GitLabCI)
 * @param yamlContent Generated YAML configuration content
 * @param autoRegenerateOnFailure Enable auto-regeneration on test failure
 * @param triggerOn List of events that trigger the workflow
 */
data class CIConfig(
    val provider: CIProvider = CIProvider.GitHubActions,
    val yamlContent: String = "",
    val autoRegenerateOnFailure: Boolean = true,
    val triggerOn: List<String> = listOf("pull_request", "push")
)

// ================================================================
// State / 状态
// ================================================================

/**
 * ============================================================
 * GeminiTestQualityState — 工具包页面状态
 * ================================================================
 * Immutable UI state — single source of truth for the entire toolkit.
 *
 * @param selectedTab Currently selected navigation tab
 * @param generatedTests List of Gemini-generated test files
 * @param qualityScore Aggregated quality metrics
 * @param coverageHeatmap Branch-level coverage data
 * @param selectedFramework Currently selected test framework
 * @param coverageStrategy Coverage strategy configuration
 * @param specTemplates Available test spec templates
 * @param activeSpec Currently active spec template
 * @param traceabilityRecords Source change → test impact records
 * @param blindSpots Detected uncovered code paths
 * @param ciConfig CI/CD configuration
 * @param isGenerating Whether test generation is in progress
 * @param generationProgress Generation progress (0.0-1.0)
 * @param error Error message if any operation failed
 */
data class GeminiTestQualityState(
    val selectedTab: TestQualityTab = TestQualityTab.Dashboard,
    val generatedTests: List<GeneratedTestFile> = emptyList(),
    val qualityScore: QualityScore = QualityScore(),
    val coverageHeatmap: Map<String, BranchCoverage> = emptyMap(),
    val selectedFramework: TestFramework = TestFramework.JUNIT5,
    val coverageStrategy: CoverageStrategy = CoverageStrategy(),
    val specTemplates: List<TestSpecTemplate> = emptyList(),
    val activeSpec: TestSpecTemplate? = null,
    val traceabilityRecords: List<TraceabilityRecord> = emptyList(),
    val blindSpots: List<BlindSpot> = emptyList(),
    val ciConfig: CIConfig = CIConfig(),
    val isGenerating: Boolean = false,
    val generationProgress: Float = 0f,
    val error: String? = null
) {
    /** Total generated test count / 生成测试文件总数 */
    val totalTests: Int get() = generatedTests.size

    /** Total test cases across all files / 所有文件的测试用例总数 */
    val totalTestCases: Int get() = generatedTests.sumOf { it.testCaseCount }

    /** Total missing risks across all files / 所有文件的遗漏风险总数 */
    val totalMissingRisks: Int get() = generatedTests.sumOf { it.missingRiskCount }

    /** Overall average quality score / 平均质量评分 */
    val averageQuality: Int
        get() = if (generatedTests.isEmpty()) 0
                else generatedTests.sumOf { it.qualityScore } / generatedTests.size
}

// ================================================================
// Intent / 意图
// ================================================================

/**
 * ============================================================
 * GeminiTestQualityIntent — 用户操作意图
 * ================================================================
 * Sealed class representing all possible user intentions.
 */
sealed class GeminiTestQualityIntent {
    /** 加载仪表盘数据 */
    data object LoadDashboard : GeminiTestQualityIntent()

    /** 切换 Tab */
    data class SelectTab(val tab: TestQualityTab) : GeminiTestQualityIntent()

    /** 生成测试（指定源文件和框架） */
    data class GenerateTests(
        val sourceFile: String,
        val framework: TestFramework
    ) : GeminiTestQualityIntent()

    /** 评估指定测试文件的质量 */
    data class EvaluateQuality(val testFile: String) : GeminiTestQualityIntent()

    /** 保存测试规范模板 */
    data class SaveSpecTemplate(val template: TestSpecTemplate) : GeminiTestQualityIntent()

    /** 删除测试规范模板 */
    data class DeleteSpecTemplate(val templateId: String) : GeminiTestQualityIntent()

    /** 激活指定规范模板 */
    data class ActivateSpec(val templateId: String) : GeminiTestQualityIntent()

    /** 生成 CI/CD 配置 */
    data class GenerateCIConfig(val ciProvider: CIProvider) : GeminiTestQualityIntent()

    /** 分析测试盲区 */
    data object AnalyzeBlindSpots : GeminiTestQualityIntent()

    /** 刷新全部数据 */
    data object RefreshAll : GeminiTestQualityIntent()

    /** 配置覆盖策略 */
    data class UpdateCoverageStrategy(val strategy: CoverageStrategy) : GeminiTestQualityIntent()

    /** 导出质量报告 */
    data object ExportReport : GeminiTestQualityIntent()
}

// ================================================================
// Effect / 副作用
// ================================================================

/**
 * ============================================================
 * GeminiTestQualityEffect — 一次性副作用
 * ================================================================
 * One-time side effects triggered by ViewModel.
 */
sealed class GeminiTestQualityEffect {
    /** 显示操作结果提示 */
    data class ShowSnackbar(val message: String) : GeminiTestQualityEffect()

    /** 导出报告成功 */
    data class ExportReport(val filePath: String) : GeminiTestQualityEffect()

    /** 导航到测试文件 */
    data class NavigateToTestFile(val filePath: String) : GeminiTestQualityEffect()

    /** 运行 CI 验证 */
    data class RunCIValidation(val configYaml: String) : GeminiTestQualityEffect()

    /** 生成完成通知 */
    data class GenerationCompleted(val testFileName: String, val testCaseCount: Int) : GeminiTestQualityEffect()
}
