package com.gcp.agents.cli.iam.policy

import com.gcp.agents.cli.model.GcpIamPolicy

/**
 * IamPolicyGenerator — 生成 GCP IAM Policy YAML
 * Generates GCP IAM Policy YAML for agent deployments.
 *
 * @property projectId GCP 项目 ID / GCP project ID
 */
class IamPolicyGenerator(
    private val projectId: String
) {
    /**
     * 为 Vertex AI 生成 IAM Policy / Generate IAM policy for Vertex AI
     * @param policy IAM 策略配置 / IAM policy configuration
     * @return YAML 格式的 IAM Policy / IAM policy in YAML format
     */
    fun generateVertexAiPolicy(policy: GcpIamPolicy): String {
        return buildString {
            appendLine("# GCP IAM Policy for Vertex AI Agent")
            appendLine("# Generated by agents-cli-sdk")
            appendLine("version: 1")
            appendLine("bindings:")
            appendLine("  - role: roles/aiplatform.user")
            appendLine("    members:")
            policy.allowedResources.forEach { resource ->
                appendLine("      - $resource")
            }
            if (policy.serviceAccountEmail != null) {
                appendLine("  - role: roles/iam.serviceAccountUser")
                appendLine("    members:")
                appendLine("      - serviceAccount:${policy.serviceAccountEmail}")
            }
        }
    }

    /**
     * 为 Cloud Run 生成 IAM Policy / Generate IAM policy for Cloud Run
     * @param policy IAM 策略配置 / IAM policy configuration
     * @param serviceName Cloud Run 服务名称 / Cloud Run service name
     * @return YAML 格式的 IAM Policy / IAM policy in YAML format
     */
    fun generateCloudRunPolicy(policy: GcpIamPolicy, serviceName: String): String {
        return buildString {
            appendLine("# GCP IAM Policy for Cloud Run Agent")
            appendLine("# Generated by agents-cli-sdk")
            appendLine("version: 1")
            appendLine("bindings:")
            appendLine("  - role: roles/run.invoker")
            appendLine("    members:")
            policy.allowedResources.forEach { resource ->
                appendLine("      - $resource")
            }
            appendLine("  - role: roles/iam.serviceAccountUser")
            appendLine("    members:")
            if (policy.serviceAccountEmail != null) {
                appendLine("      - serviceAccount:${policy.serviceAccountEmail}")
            }
        }
    }

    /**
     * 为 GKE 生成 IAM Policy / Generate IAM policy for GKE
     * @param policy IAM 策略配置 / IAM policy configuration
     * @param cluster GKE 集群名称 / GKE cluster name
     * @param namespace Kubernetes 命名空间 / Kubernetes namespace
     * @return YAML 格式的 IAM Policy / IAM policy in YAML format
     */
    fun generateGkePolicy(policy: GcpIamPolicy, cluster: String, namespace: String): String {
        return buildString {
            appendLine("# GCP IAM Policy for GKE Agent")
            appendLine("# Generated by agents-cli-sdk")
            appendLine("version: 1")
            appendLine("bindings:")
            appendLine("  - role: roles/container.developer")
            appendLine("    members:")
            policy.allowedResources.forEach { resource ->
                appendLine("      - $resource")
            }
            appendLine("  - role: roles/container.serviceAccountUser")
            appendLine("    members:")
            if (policy.serviceAccountEmail != null) {
                appendLine("      - serviceAccount:${projectId}.svc.id.goog[${namespace}/default]")
            }
        }
    }

    /**
     * 生成完整的 IAM Policy 文档 / Generate complete IAM policy document
     * @param policy IAM 策略配置 / IAM policy configuration
     * @param targetService 目标 GCP 服务 / Target GCP service
     * @return 完整的 IAM Policy / Complete IAM policy
     */
    fun generatePolicy(policy: GcpIamPolicy, targetService: String): String {
        return when {
            targetService.contains("vertex") || targetService.contains("aiplatform") -> generateVertexAiPolicy(policy)
            targetService.contains("run") -> generateCloudRunPolicy(policy, targetService)
            targetService.contains("gke") || targetService.contains("container") -> generateGkePolicy(policy, targetService, "default")
            else -> generateVertexAiPolicy(policy) // Default to Vertex AI
        }
    }
}
