package com.gcp.agents.cli.ci.gitlab

/**
 * GitLabCiTemplateGenerator — 生成 GitLab CI YAML 片段
 * Generates GitLab CI YAML template fragments.
 */
class GitLabCiTemplateGenerator {

    /**
     * 生成完整的 .gitlab-ci.yml 模板 / Generate complete .gitlab-ci.yml template
     */
    fun generateGitLabCiYaml(projectId: String, defaultRegion: String = "us-central1"): String {
        return """
            # Generated by agents-cli-sdk
            image: google/cloud-sdk:latest

            stages:
              - deploy-agent
              - audit-agent

            variables:
              GCP_PROJECT_ID: "${projectId}"
              GCP_REGION: "${defaultRegion}"

            deploy-agent:
              stage: deploy-agent
              image: google/cloud-sdk:latest
              script:
                - agents-cli agent deploy --name ${'$'}AGENT_NAME --target ${'$'}TARGET_SERVICE
              variables:
                AGENT_NAME: "default-agent"
                TARGET_SERVICE: "vertex-ai"

            audit-agent:
              stage: audit-agent
              image: google/cloud-sdk:latest
              script:
                - agents-cli audit export --format bigquery
              only:
                - schedules
        """.trimIndent()
    }

    /**
     * 生成 deploy-agent job 片段 / Generate deploy-agent job fragment
     */
    fun generateDeployJobFragment(): String {
        return """
            deploy-agent:
              stage: deploy-agent
              image: google/cloud-sdk:latest
              script:
                - agents-cli agent deploy --name ${'$'}AGENT_NAME --target ${'$'}TARGET_SERVICE
        """.trimIndent()
    }

    /**
     * 验证 YAML 语法 / Validate YAML syntax
     */
    fun validateYaml(yamlContent: String): Boolean {
        return try {
            val parser = org.yaml.snakeyaml.Yaml()
            val result: Any? = parser.load(yamlContent)
            result != null
        } catch (e: Exception) {
            false
        }
    }
}
