package com.gcp.agents.cli.ci.gitlab

/**
 * GitLabCiTemplateGenerator — 生成 GitLab CI YAML 片段
 * Generates GitLab CI YAML template fragments.
 */
class GitLabCiTemplateGenerator {

    /**
     * 生成完整的 .gitlab-ci.yml 模板 / Generate complete .gitlab-ci.yml template
     * @param projectId GCP 项目 ID / GCP project ID
     * @param defaultRegion 默认 GCP 区域 / Default GCP region
     * @return GitLab CI YAML 内容 / GitLab CI YAML content
     */
    fun generateGitLabCiYaml(
        projectId: String,
        defaultRegion: String = "us-central1"
    ): String {
        return """
            # Generated by agents-cli-sdk
            # GitLab CI template for Google agents-cli SDK
            # Version: 1.0.0

            image: google/cloud-sdk:latest

            stages:
              - deploy-agent
              - audit-agent
              - cleanup

            variables:
              GCP_PROJECT_ID: "${projectId}"
              GCP_REGION: "${defaultRegion}"
              AGENTS_CLI_VERSION: "latest"

            # Agent deployment job
            deploy-agent:
              stage: deploy-agent
              image: google/cloud-sdk:latest
              before_script:
                - echo "Installing agents-cli..."
                - gcloud components install agents-cli || true
                - echo "Setting up GCP authentication..."
                - echo "${'$'}GCP_SERVICE_ACCOUNT" > /tmp/key.json
                - gcloud auth activate-service-account --key-file=/tmp/key.json
                - gcloud config set project ${'$'}GCP_PROJECT_ID
              script:
                - |
                  agents-cli agent deploy \
                    --name ${'$'}AGENT_NAME \
                    --source ${'$'}AGENT_SOURCE \
                    --target ${'$'}TARGET_SERVICE \
                    --region ${'$'}GCP_REGION \
                    --iam-policy-file ${'$'}IAM_POLICY_FILE \
                    --output json > deployment_result.json
                - |
                  cat deployment_result.json | jq -r '.endpoint' > agent_endpoint.txt
                  cat deployment_result.json | jq -r '.instanceId' > agent_instance_id.txt
              artifacts:
                paths:
                  - deployment_result.json
                  - agent_endpoint.txt
                  - agent_instance_id.txt
                expire_in: 7 days
              environment:
                name: ${'$'}DEPLOYMENT_ENV
                url: ${'$'}AGENT_ENDPOINT
              only:
                - main
                - develop
                - tags
              except:
                - schedules
              variables:
                AGENT_NAME: "default-agent"
                AGENT_SOURCE: "github:owner/repo:main"
                TARGET_SERVICE: "vertex-ai"
                DEPLOYMENT_ENV: "staging"

            # Audit agent job
            audit-agent:
              stage: audit-agent
              image: google/cloud-sdk:latest
              before_script:
                - gcloud auth activate-service-account --key-file=/tmp/key.json
                - gcloud config set project ${'$'}GCP_PROJECT_ID
              script:
                - |
                  agents-cli audit export \
                    --format ${'$'}AUDIT_FORMAT \
                    --destination ${'$'}AUDIT_DESTINATION \
                    --project ${'$'}GCP_PROJECT_ID
              artifacts:
                paths:
                  - audit_report.*
                expire_in: 30 days
              only:
                - schedules
              variables:
                AUDIT_FORMAT: "bigquery"
                AUDIT_DESTINATION: "${projectId}.audit.audit_logs"

            # Agent status check job
            check-agent-status:
              stage: deploy-agent
              image: google/cloud-sdk:latest
              before_script:
                - gcloud auth activate-service-account --key-file=/tmp/key.json
                - gcloud config set project ${'$'}GCP_PROJECT_ID
              script:
                - |
                  AGENT_STATUS=$(agents-cli agent status --name ${'$'}AGENT_NAME --output json | jq -r '.status')
                  echo "Agent status: ${'$'}AGENT_STATUS"
                  if [ "${'$'}AGENT_STATUS" != "RUNNING" ]; then
                    echo "Agent is not running!"
                    exit 1
                  fi
              only:
                - main
                - develop
              variables:
                AGENT_NAME: "default-agent"

            # Cleanup agent job (manual trigger)
            cleanup-agent:
              stage: cleanup
              image: google/cloud-sdk:latest
              before_script:
                - gcloud auth activate-service-account --key-file=/tmp/key.json
                - gcloud config set project ${'$'}GCP_PROJECT_ID
              script:
                - |
                  agents-cli agent delete \
                    --name ${'$'}AGENT_NAME \
                    --instance-id ${'$'}AGENT_INSTANCE_ID \
                    --force
              when: manual
              variables:
                AGENT_NAME: "default-agent"
                AGENT_INSTANCE_ID: ""

            # Predefined job templates
            .deploy-template:
              image: google/cloud-sdk:latest
              before_script:
                - gcloud auth activate-service-account --key-file=/tmp/key.json
                - gcloud config set project ${'$'}GCP_PROJECT_ID

            # Security scan with agent
            security-scan:
              extends: .deploy-template
              stage: deploy-agent
              script:
                - |
                  agents-cli agent invoke security-agent \
                    --input "repository:${'$'}CI_REPOSITORY_URL" \
                    --output security_report.json
              artifacts:
                paths:
                  - security_report.json
              allow_failure: true
        """.trimIndent()
    }

    /**
     * 生成单独的 deploy-agent job 片段 / Generate standalone deploy-agent job fragment
     */
    fun generateDeployJobFragment(): String {
        return """
            deploy-agent:
              stage: deploy-agent
              image: google/cloud-sdk:latest
              script:
                - agents-cli agent deploy --name ${'$'}AGENT_NAME --target ${'$'}TARGET_SERVICE
              variables:
                AGENT_NAME: "default-agent"
                TARGET_SERVICE: "vertex-ai"
        """.trimIndent()
    }

    /**
     * 生成单独的 audit-agent job 片段 / Generate standalone audit-agent job fragment
     */
    fun generateAuditJobFragment(): String {
        return """
            audit-agent:
              stage: audit
              image: google/cloud-sdk:latest
              script:
                - agents-cli audit export --format bigquery
              only:
                - schedules
        """.trimIndent()
    }

    /**
     * 验证 YAML 语法 / Validate YAML syntax
     * @param yamlContent YAML 内容 / YAML content
     * @return 是否有效 / Whether valid
     */
    fun validateYaml(yamlContent: String): Boolean {
        return try {
            org.yaml.snakeyaml.Yaml().load(yamlContent) != null
        } catch (e: Exception) {
            false
        }
    }
}
